version: '3.9'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    image: cowlar/todo-frontend
    depends_on:
      - backend
    networks:
      - frontend-network

  backend:
    build:
      context: ./backend
    ports:
      - '8080:8080'
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017/cowlar
      - PORT=8080
    image: cowlar/todo-backend
    depends_on:
      - mongo
    networks:
      - backend-network
      - frontend-network
    volumes:
      - ./frontend/dist:/app/dist # Mount the frontend build files for the backend to serve

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - backend-network
    volumes:
      - mongo-data:/data/db

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
